export enum StaffLanguage {
  JAPANESE = 'JAPANESE',
  ENGLISH = 'ENGLISH',
  KOREAN = 'KOREAN',
  ITALIAN = 'ITALIAN',
  SPANISH = 'SPANISH',
  PORTUGUESE = 'PORTUGUESE',
  FRENCH = 'FRENCH',
  GERMAN = 'GERMAN',
  HEBREW = 'HEBREW',
  HUNGARIAN = 'HUNGARIAN',
}
