export enum StaffSort {
  ID = 'ID',
  ID_DESC = 'ID_DESC',
  ROLE = 'ROLE',
  ROLE_DESC = 'ROLE_DESC',
  LANGUAGE = 'LANGUAGE',
  LANGUAGE_DESC = 'LANGUAGE_DESC',
  SEARCH_MATCH = 'SEARCH_MATCH',
  FAVOURITES = 'FAVOURITES',
  FAVOURITES_DESC = 'FAVOURITES_DESC',
}
