export enum MediaSource {
  ANIME = 'ANIME',
  DOUJINSHI = 'DOUJINSHI',
  LIGHT_NOVEL = 'LIGHT_NOVEL',
  MANGA = 'MANGA',
  NOVEL = 'NOVEL',
  ORIGINAL = 'ORIGINAL',
  OTHER = 'OTHER',
  VIDEO_GAME = 'VIDEO_GAME',
  VISUAL_NOVEL = 'VISUAL_NOVEL',
}
